version: '3.9'

services:
  app:
    container_name: app_container
    build: .
    entrypoint: .docker/entrypoint.sh
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/db
    container_name: postgres_container
    tty: true
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    tty: true
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_LISTEN_PORT}:80
    restart: unless-stopped
    depends_on:
      - db

networks:
  default:
    driver: bridge

volumes:
  pgadmin:
